#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 23 14:39:38 2020

@author: pi
"""

#n = int(input("digite un numero: "))
#
#if n>0:
#    print("Numero positivo")
#    
#elif n<0:
#    print("Numero negativo")
#    
#else:
#    print("el numero es el cero0")

n1 = int(input("digite el numero 1:"))
n2 = int(input("digite el numero 2:"))

if n1>n2:
    print("El mayor es:",n1)
elif n1<n2:
    print("El mayor es:",n2)
else:
    print("Son iguales")
    