#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 23 14:51:26 2020

@author: pi
"""

#n = int(input("Digite un numero: "))
#s=0
#while n >= 0:
#    print(n)
#    n=n-1
#print("Fin de programa")

#n = int(input("Digite un numero: "))
#s=0
#while n >= 0:
#    print(s)
#    s=s+1
#    n=n-1
#print("Fin de programa")

a = True
while a == True:
    b = input("Digite algo: ")
    if b == "fin":
        a = False
    else:
        if int(b)%2 == 0:
            print("El numero es par")
        else:
            print("El numero es impar")
print("fin de programa")
        